"""add init table

Revision ID: 0018ac87022d
Revises: 
Create Date: 2020-10-24 22:56:16.602500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0018ac87022d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shopID', sa.String(length=64), nullable=True),
    sa.Column('shopName', sa.String(length=64), nullable=True),
    sa.Column('shopURL', sa.String(length=128), nullable=True),
    sa.Column('sellerName', sa.String(length=64), nullable=True),
    sa.Column('sellerURL', sa.String(length=128), nullable=True),
    sa.Column('sellerUid', sa.String(length=64), nullable=True),
    sa.Column('sellerWangWangOnlineStatus', sa.String(length=16), nullable=True),
    sa.Column('sellerWangWangURL', sa.String(length=128), nullable=True),
    sa.Column('goodCommentRatio', sa.String(length=16), nullable=True),
    sa.Column('isConsumerInsure', sa.Boolean(), nullable=True),
    sa.Column('isGoldSeller', sa.Boolean(), nullable=True),
    sa.Column('numberOfFans', sa.Integer(), nullable=True),
    sa.Column('shopZone', sa.String(length=16), nullable=True),
    sa.Column('numberOfItems', sa.Integer(), nullable=True),
    sa.Column('openingDate', sa.DateTime(), nullable=True),
    sa.Column('DSR_value', sa.Integer(), nullable=True),
    sa.Column('shopCategory', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shops_shopID'), 'shops', ['shopID'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_shops_shopID'), table_name='shops')
    op.drop_table('shops')
    # ### end Alembic commands ###
